In [1]:
import pandas as pd

In [49]:
pip install sqlalchemy psycopg2 pandas openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (2.0.46)
Collecting psycopg2
  Downloading psycopg2-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: pandas in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (3.0.1)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.3)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ------- -------------------------------- 0.5/2.7 MB 176.5 kB/s eta 0:00:13
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   ----------- ---------------------------- 0.8/2.7 MB 84.1 kB/s eta 0:00:23
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   --------------- ------------------------ 1.0/2.7 MB 63.7 kB/s eta 0:00:27
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ------------------- -------------------- 1.3/2.7 MB 63.7 kB/s eta 0:00:23
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   ----------------------- ---------------- 1.6/2.7 MB 57.7 kB/s eta 0:00:20
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   --------------------------- ------------ 1.8/2.7 MB 55.1 kB/s eta 0:00:16
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ------------------------------ --------- 2.1/2.7 MB 46.7 kB/s eta 0:00:14
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10
   ---------------------------------- ----- 2.4/2.7 MB 36.5 kB/s eta 0:00:10

In [2]:
df = pd.read_csv('superstore.csv')
df.head(5)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [3]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('.','_')
df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', '记录数', 'order_date', 'order_id', 'order_priority',
       'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id',
       'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state',
       'sub_category', 'year', 'market2', 'weeknum'],
      dtype='str')

In [4]:
column = [col for col in df.columns if df[col].nunique() == 1]
column

['记录数']

In [5]:
print(df['记录数'].value_counts())  

# this column has only 1 unique values so deleting this column
df.drop(columns = ['记录数'],inplace = True)

记录数
1    51290
Name: count, dtype: int64

In [6]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        51290 non-null  str
 1   city            51290 non-null  str
 2   country         51290 non-null  str
 3   customer_id     51290 non-null  str
 4   customer_name   51290 non-null  str
 5   discount        51290 non-null  float64
 6   market          51290 non-null  str
 7   order_date      51290 non-null  datetime64[us]
 8   order_id        51290 non-null  str
 9   order_priority  51290 non-null  str
 10  product_id      51290 non-null  str
 11  product_name    51290 non-null  str
 12  profit          51290 non-null  float64
 13  quantity        51290 non-null  int64
 14  region          51290 non-null  str
 15  row_id          51290 non-null  int64
 16  sales           51290 non-null  int64
 17  segment         51290 non-null  str
 18  ship_date       51290 non-null  datetime64[us]
 19  ship_mode       51290 non-null  str
 20  shipping_cost   51290 non-null  float64
 21  state           51290 non-null  str
 22  sub_category    51290 non-null  str
 23  year            51290 non-null  int64
 24  market2         51290 non-null  str
 25  weeknum         51290 non-null  int64
dtypes: datetime64[us](2), float64(3), int64(5), str(16)
memory usage: 18.6 MB

### Customers Table

In [8]:
customers_df = df[["customer_id", "customer_name", "segment"]].drop_duplicates()
customers_df.head()

  customer_id     customer_name   segment
0   LS-172304  Lycoris Saunders  Consumer
1   MV-174854     Mark Van Huff  Consumer
2   CS-121304      Chad Sievert  Consumer
4   AP-109154    Arthur Prichep  Consumer
5   JF-154904      Jeremy Farry  Consumer

In [10]:
customers_df.to_csv('Customers.csv',index = False)

In [11]:
import pandas as pd

customers_df = pd.read_csv("customers.csv")
customers_df.head()

  customer_id     customer_name   segment
0   LS-172304  Lycoris Saunders  Consumer
1   MV-174854     Mark Van Huff  Consumer
2   CS-121304      Chad Sievert  Consumer
3   AP-109154    Arthur Prichep  Consumer
4   JF-154904      Jeremy Farry  Consumer

In [12]:
import pandas as pd
from sqlalchemy import create_engine

# DB connection (replace password & db name)
engine = create_engine("postgresql+psycopg2://postgres:2209@localhost:5432/super_store_analysis")
customers_df.to_sql("customers", con=engine, if_exists="replace", index=False)

873

### Location Table

In [13]:
location_df = df[['country','state','city','region','market','market2']].drop_duplicates().reset_index(drop = True)
location_df['location_id'] = location_df.index+1
location_df

,country,state,city,region,market,market2,location_id
0,United States,California,Los Angeles,West,US,North America,1
1,United States,California,San Francisco,West,US,North America,2
2,United States,California,San Diego,West,US,North America,3
3,United States,California,Roseville,West,US,North America,4
4,United States,California,Huntington Beach,West,US,North America,5
...,...,...,...,...,...,...,...
3814,United States,California,Lake Elsinore,West,US,North America,3815
3815,United States,California,Dublin,West,US,North America,3816
3816,United States,California,Ontario,West,US,North America,3817
3817,United States,California,Whittier,West,US,North America,3818
3818,United States,California,Redwood City,West,US,North America,3819

In [14]:
location_df.to_csv('Location.csv', index = False)

In [15]:
# DB connection (replace password & db name)
engine = create_engine("postgresql+psycopg2://postgres:2209@localhost:5432/super_store_analysis")

location_df.to_sql("location", con=engine, if_exists="replace", index=False)

819

### Product Table

In [16]:
products_df = df[['product_id','product_name','category','sub_category']].drop_duplicates()
products_df

,product_id,product_name,category,sub_category
0,OFF-PA-10002005,Xerox 225,Office Supplies,Paper
1,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",Office Supplies,Paper
2,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",Office Supplies,Paper
3,OFF-PA-10001144,Xerox 1913,Office Supplies,Paper
4,OFF-PA-10002105,Xerox 223,Office Supplies,Paper
...,...,...,...,...
50952,TEC-PH-10001949,Cisco SPA 501G IP Phone,Technology,Phones
51038,TEC-MA-10003246,Hewlett-Packard Deskjet D4360 Printer,Technology,Machines
51050,TEC-MA-10003329,"Vtech AT&T CL2940 Corded Speakerphone, Black",Technology,Machines
51077,FUR-TA-10001691,Barricks Non-Folding Utility Table with Steel ...,Furniture,Tables
51109,TEC-MA-10001031,Socket Bluetooth Cordless Hand Scanner (CHS),Technology,Machines

In [17]:
products_df.to_csv('Products.csv',index = False)

In [18]:
# DB connection (replace password & db name)
engine = create_engine("postgresql+psycopg2://postgres:2209@localhost:5432/super_store_analysis")

products_df.to_sql("products", con=engine, if_exists="replace", index=False)

768

### Shipping Table

In [19]:
shipping_df = df[['ship_mode','shipping_cost','order_priority']].drop_duplicates().reset_index(drop = True)
shipping_df['ship_id'] = shipping_df.index + 1  
shipping_df.head()

        ship_mode  shipping_cost order_priority  ship_id
0    Second Class           4.37           High        1
1  Standard Class           0.94         Medium        2
2  Standard Class           1.81         Medium        3
3  Standard Class           4.59         Medium        4
4  Standard Class           1.32           High        5

In [20]:
shipping_df.to_csv('Shipping.csv',index = False)

In [21]:
# DB connection (replace password & db name)
engine = create_engine("postgresql+psycopg2://postgres:2209@localhost:5432/super_store_analysis")

shipping_df.to_sql("shipping", con=engine, if_exists="replace", index=False)

546

### Orders Table

In [24]:
orders_df = df.merge(
    location_df,
    on=["country", "state", "city", "region", "market", "market2"]
)

orders_df = orders_df.merge(
    shipping_df,
    on=["ship_mode", "shipping_cost", "order_priority"]
)

orders_df = orders_df[[
    "order_id", "order_date", "ship_date", "year", "weeknum",
    "customer_id", "product_id", "location_id", "ship_id",
    "sales", "quantity", "discount", "profit"
]]

In [25]:
orders_df.to_csv('Orders.csv',index = False)

In [26]:
orders_df

,order_id,order_date,ship_date,year,weeknum,customer_id,product_id,location_id,ship_id,sales,quantity,discount,profit
0,CA-2011-130813,2011-01-07,2011-01-09,2011,2,LS-172304,OFF-PA-10002005,1,1,19,3,0.0,9.3312
1,CA-2011-148614,2011-01-21,2011-01-26,2011,4,MV-174854,OFF-PA-10002893,1,2,19,2,0.0,9.2928
2,CA-2011-118962,2011-08-05,2011-08-09,2011,32,CS-121304,OFF-PA-10000659,1,3,21,3,0.0,9.8418
3,CA-2011-118962,2011-08-05,2011-08-09,2011,32,CS-121304,OFF-PA-10001144,1,4,111,2,0.0,53.2608
4,CA-2011-146969,2011-09-29,2011-10-03,2011,40,AP-109154,OFF-PA-10002105,1,5,6,1,0.0,3.1104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-109701,2014-12-03,2014-12-04,2014,49,AM-103604,OFF-BI-10000632,1,18500,69,2,0.2,22.5732
51286,CA-2014-109701,2014-12-03,2014-12-04,2014,49,AM-103604,OFF-BI-10004187,1,6869,9,6,0.2,3.1584
51287,CA-2014-106964,2014-12-18,2014-12-21,2014,51,HR-147704,OFF-BI-10000320,1,7551,12,2,0.2,4.2804
51288,CA-2014-145219,2014-12-25,2014-12-26,2014,52,RM-196754,OFF-BI-10001670,1,30546,90,3,0.2,33.9300
51289,CA-2014-121398,2014-12-26,2014-12-30,2014,52,FH-143654,OFF-BI-10001718,1,2319,154,3,0.2,51.8238

In [27]:
# DB connection (replace password & db name)
engine = create_engine("postgresql+psycopg2://postgres:2209@localhost:5432/super_store_analysis")

orders_df.to_sql("orders", con=engine, if_exists="replace", index=False)

290